name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create post-build script
        run: |
          mkdir -p scripts
          cat > scripts/post-build.js << 'EOF'
          const fs = require('fs');
          const path = require('path');

          const outDir = path.join(__dirname, '..', 'out');

          // Ensure the out directory exists
          if (!fs.existsSync(outDir)) {
            console.error('❌ Output directory not found. Make sure the build completed successfully.');
            process.exit(1);
          }

          // Create .nojekyll file
          fs.writeFileSync(path.join(outDir, '.nojekyll'), '');
          console.log('✅ Created .nojekyll file');

          // Create 404.html file
          const notFoundContent = `<!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Page Not Found</title>
            <style>
              body {
                background-color: #0A0A0A;
                color: white;
                font-family: Arial, sans-serif;
                height: 100vh;
                margin: 0;
                display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;
              }
              h1 { font-size: 4rem; margin-bottom: 1rem; }
              p { font-size: 1.25rem; color: #d1d1d1; margin-bottom: 2rem; }
              a { color: #60a5fa; text-decoration: underline; }
              a:hover { color: #93c5fd; }
            </style>
          </head>
          <body>
            <div>
              <h1>404</h1>
              <p>Page not found</p>
              <a href="/">Return to Homepage</a>
            </div>
          </body>
          </html>`;
          fs.writeFileSync(path.join(outDir, '404.html'), notFoundContent);
          console.log('✅ Created 404.html file');

          console.log('✅ Post-build completed successfully!');
          EOF

      - name: Fix Node.js platform differences
        run: |
          sed -i 's/set NODE_OPTIONS=--max-old-space-size=4096 &&/export NODE_OPTIONS=--max-old-space-size=4096 \&\& /' package.json
          
      - name: Modify next.config.js for GitHub Pages 
        run: |
          cat > next.config.js << 'EOF'
          /** @type {import('next').NextConfig} */

          const nextConfig = {
            output: 'export',
            images: {
              unoptimized: true,
            },
            basePath: '',
            trailingSlash: true,
            eslint: {
              ignoreDuringBuilds: true,
            },
            typescript: {
              ignoreBuildErrors: true
            }
          }

          module.exports = nextConfig
          EOF

      - name: Build
        run: |
          npm run build
        env:
          NODE_ENV: production
          NEXT_SKIP_TYPE_CHECK: true
          NEXT_SKIP_LINT: true

      - name: Run post-build script
        run: node scripts/post-build.js

      - name: Configure Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 